[package]
name = "load-tester"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
device-logic = { path = "../device-logic" }
anyhow = "1.0" # Per una gestione degli errori più semplice nel main